version: '3.8'

services:
  xdc-price-poker:
    environment:
      AWS_SECRET_ID: borrow-apothem-secret

x-aws-cloudformation:
  Resources:
    Secret:
      Properties:
        Name: 'borrow-apothem-secret'
        SecretString: '{"POKER_WALLET_PRIVATE_KEY": "${POKER_WALLET_PRIVATE_KEY}"}'
      Type: AWS::SecretsManager::Secret

    NginxTCP443Listener:
      Properties:
        Certificates:
          - CertificateArn: 'arn:aws:acm:ap-south-1:135135176603:certificate/60d2b9e4-65d6-468c-9e90-3de1c8ace136'
        Protocol: HTTPS

    Xdcpricepoker3001Listener:
      Properties:
        Certificates:
          - CertificateArn: 'arn:aws:acm:ap-south-1:135135176603:certificate/60d2b9e4-65d6-468c-9e90-3de1c8ace136'
        Protocol: HTTPS
