version: '3.8'

volumes:
  postgres-data:

services:
  db:
    image: postgres:12.10-alpine3.15
    volumes:
      - postgres-data:/var/lib/postgresql/data
    environment:
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}

  xdc-price-poker-apothem:
    ports:
      - target: 3001
        published: 3001
        x-aws-protocol: http

    environment:
      POKE_TARGET_CONTRACT: '0x6911b072DC16Dcc5B55caB7a832cBfcfB3E45069'
      POKER_CONTRACT: '0x87606d843426a59c47c6574FeFc2Ca98feA0A170'
      OSM: '["0x4e1955cCdE51fc1cF58757fdF114839de100837f"]'
      JSON_RPC_NODE_URL: 'https://rpc-apothem.xinfin.yodaplus.net'
      PORT: 3001

  xdc-price-poker-mainnet:
    ports:
      - target: 3002
        published: 3002
        x-aws-protocol: http

    environment:
      POKE_TARGET_CONTRACT: '0xfB8dC4f798ad575c590037D9192123cbeCbc84A0'
      POKER_CONTRACT: '0xC4209Ad04c816cC79C837eBdA2199957cBd5d142'
      OSM: '["0x4af25dcAC2c13117726202B65f5B21AfD077a078"]'
      JSON_RPC_NODE_URL: 'https://rpc.xinfin.yodaplus.net'
      PORT: 3002

  nginx:
    depends_on:
      - nextjs
    ports:
      - '80:80'
      - '443:443'

  nextjs:
    depends_on:
      - db

    deploy:
      resources:
        limits:
          cpus: '0.5'
          memory: 4Gb

    environment:
      COMMIT_SHA: ${COMMIT_SHA}
      API_HOST: ${API_HOST}
      MIXPANEL_ENV: ${MIXPANEL_ENV}
      MIXPANEL_KEY: ${MIXPANEL_KEY}
      INFURA_PROJECT_ID: ${INFURA_PROJECT_ID}
      ETHERSCAN_API_KEY: ${ETHERSCAN_API_KEY}
      SHOW_BUILD_INFO: ${SHOW_BUILD_INFO}
      MULTIPLY_PROXY_ACTIONS: ${MULTIPLY_PROXY_ACTIONS}
      EXCHANGE: ${EXCHANGE}
      DUMMY_EXCHANGE: ${DUMMY_EXCHANGE}
      USE_DUMMY: ${USE_DUMMY}
      CHALLENGE_JWT_SECRET: ${CHALLENGE_JWT_SECRET}
      USER_JWT_SECRET: ${USER_JWT_SECRET}
      USE_TERMS_OF_SERVICE: ${USE_TERMS_OF_SERVICE}
      NODE_ENV: 'production'
      DATABASE_URL: postgresql://postgres:${POSTGRES_PASSWORD}@db:5432/postgres
