version: '3.8'

volumes:
  postgres-data:

services:
  db:
    image: postgres:12.10-alpine3.15
    volumes:
      - postgres-data:/var/lib/postgresql/data
    environment:
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}

  nginx:
    depends_on:
      - nextjs
    ports:
      - '80:80'
      - '443:443'

  nextjs:
    depends_on:
      - db

    environment:
      COMMIT_SHA: ${COMMIT_SHA}
      API_HOST: ${API_HOST}
      MIXPANEL_ENV: ${MIXPANEL_ENV}
      MIXPANEL_KEY: ${MIXPANEL_KEY}
      INFURA_PROJECT_ID: ${INFURA_PROJECT_ID}
      ETHERSCAN_API_KEY: ${ETHERSCAN_API_KEY}
      SHOW_BUILD_INFO: ${SHOW_BUILD_INFO}
      MULTIPLY_PROXY_ACTIONS: ${MULTIPLY_PROXY_ACTIONS}
      EXCHANGE: ${EXCHANGE}
      DUMMY_EXCHANGE: ${DUMMY_EXCHANGE}
      USE_DUMMY: ${USE_DUMMY}
      CHALLENGE_JWT_SECRET: ${CHALLENGE_JWT_SECRET}
      USER_JWT_SECRET: ${USER_JWT_SECRET}
      USE_TERMS_OF_SERVICE: ${USE_TERMS_OF_SERVICE}
      NODE_ENV: 'production'
      DATABASE_URL: postgresql://postgres:${POSTGRES_PASSWORD}@db:5432/postgres
