version: '3.8'

x-aws-cloudformation:
  Resources:
    XdcpricepokerapothemService:
      Properties:
        DeploymentConfiguration:
          MaximumPercent: 100
          MinimumHealthyPercent: 0

    XdcpricepokermainnetService:
      Properties:
        DeploymentConfiguration:
          MaximumPercent: 100
          MinimumHealthyPercent: 0

    DbService:
      Properties:
        DeploymentConfiguration:
          MaximumPercent: 100
          MinimumHealthyPercent: 0

    SecretReadRoleApothem:
      Properties:
        AssumeRolePolicyDocument:
          Statement:
            - Action:
                - sts:AssumeRole
              Condition: {}
              Effect: Allow
              Principal:
                Service: ecs-tasks.amazonaws.com
          Version: 2012-10-17
        Policies:
          - PolicyDocument:
              Statement:
                - Action:
                    - secretsmanager:GetResourcePolicy
                    - secretsmanager:GetSecretValue
                    - secretsmanager:DescribeSecret
                    - secretsmanager:ListSecretVersionIds
                  Effect: Allow
                  Resource:
                    - Ref: SecretApothem
              Version: 2012-10-17
            PolicyName: SecretsReadPolicy
      Type: AWS::IAM::Role

    SecretReadRoleMainnet:
      Properties:
        AssumeRolePolicyDocument:
          Statement:
            - Action:
                - sts:AssumeRole
              Condition: {}
              Effect: Allow
              Principal:
                Service: ecs-tasks.amazonaws.com
          Version: 2012-10-17
        Policies:
          - PolicyDocument:
              Statement:
                - Action:
                    - secretsmanager:GetResourcePolicy
                    - secretsmanager:GetSecretValue
                    - secretsmanager:DescribeSecret
                    - secretsmanager:ListSecretVersionIds
                  Effect: Allow
                  Resource:
                    - Ref: SecretMainnet
              Version: 2012-10-17
            PolicyName: SecretsReadPolicy
      Type: AWS::IAM::Role

    XdcpricepokerapothemTaskDefinition:
      Properties:
        TaskRoleArn:
          Ref: SecretReadRoleApothem

    XdcpricepokermainnetTaskDefinition:
      Properties:
        TaskRoleArn:
          Ref: SecretReadRoleMainnet

    NginxTCP80TargetGroup:
      Properties:
        HealthCheckPath: /
        Matcher:
          HttpCode: 200-499

    NginxTCP443TargetGroup:
      Properties:
        HealthCheckPath: /
        Matcher:
          HttpCode: 200-499

    Xdcpricepokerapothem3001TargetGroup:
      Properties:
        HealthCheckPath: /status
        Matcher:
          HttpCode: 200-499

    Xdcpricepokermainnet3002TargetGroup:
      Properties:
        HealthCheckPath: /status
        Matcher:
          HttpCode: 200-499
